# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["kernel_upgrades", "delayed_transactions","irmin_chunks","metadata","block_storage_mode","l1_l2_finalized_levels","l1_l2_levels_relationships"] }

[migrations_directory]
dir = "/home/user/Documents/EtherlinkStart/rpcdieselserver/migrations"
